/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";
import * as generated from "./dbSchemas.gen.ts";
export type Json = z.infer<typeof generated.jsonSchema>;
export type RowAdminsType = z.infer<typeof generated.publicAdminsRowSchema>;
export type InsertAdminsType = z.infer<
  typeof generated.publicAdminsInsertSchema
>;
export type UpdateAdminsType = z.infer<
  typeof generated.publicAdminsUpdateSchema
>;
export type RowUsersType = z.infer<typeof generated.publicUsersRowSchema>;
export type InsertUsersType = z.infer<typeof generated.publicUsersInsertSchema>;
export type UpdateUsersType = z.infer<typeof generated.publicUsersUpdateSchema>;
export type IsAdminArgs = z.infer<typeof generated.publicIsAdminArgsSchema>;
export type IsAdminReturns = z.infer<
  typeof generated.publicIsAdminReturnsSchema
>;
export type IsSuperAdminArgs = z.infer<
  typeof generated.publicIsSuperAdminArgsSchema
>;
export type IsSuperAdminReturns = z.infer<
  typeof generated.publicIsSuperAdminReturnsSchema
>;
