/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";
import { type Json } from "./dbTypes.gen.ts";

export const jsonSchema: z.ZodSchema<Json> = z.lazy(() =>
  z
    .union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.string(), z.union([jsonSchema, z.undefined()])),
      z.array(jsonSchema),
    ])
    .nullable(),
);

export const publicAdminsRowSchema = z.object({
  created_at: z.string(),
  email: z.string(),
  first_name: z.string(),
  id: z.string(),
  is_super_admin: z.boolean(),
  last_name: z.string(),
  updated_at: z.string(),
});

export const publicAdminsInsertSchema = z.object({
  created_at: z.string().optional(),
  email: z.string(),
  first_name: z.string(),
  id: z.string(),
  is_super_admin: z.boolean().optional(),
  last_name: z.string(),
  updated_at: z.string().optional(),
});

export const publicAdminsUpdateSchema = z.object({
  created_at: z.string().optional(),
  email: z.string().optional(),
  first_name: z.string().optional(),
  id: z.string().optional(),
  is_super_admin: z.boolean().optional(),
  last_name: z.string().optional(),
  updated_at: z.string().optional(),
});

export const publicUsersRowSchema = z.object({
  created_at: z.string(),
  email: z.string(),
  first_name: z.string(),
  id: z.string(),
  last_name: z.string(),
  updated_at: z.string(),
});

export const publicUsersInsertSchema = z.object({
  created_at: z.string().optional(),
  email: z.string(),
  first_name: z.string(),
  id: z.string(),
  last_name: z.string(),
  updated_at: z.string().optional(),
});

export const publicUsersUpdateSchema = z.object({
  created_at: z.string().optional(),
  email: z.string().optional(),
  first_name: z.string().optional(),
  id: z.string().optional(),
  last_name: z.string().optional(),
  updated_at: z.string().optional(),
});

export const publicIsAdminArgsSchema = z.never();

export const publicIsAdminReturnsSchema = z.boolean();

export const publicIsSuperAdminArgsSchema = z.never();

export const publicIsSuperAdminReturnsSchema = z.boolean();
