/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as SandboxRouteImport } from './routes/_sandbox'
import { Route as UnauthedRouteImport } from './routes/_unauthed'
import { Route as AuthedLogoutRouteImport } from './routes/_authed/logout'
import { Route as SandboxBlocksRouteImport } from './routes/_sandbox/blocks'
import { Route as SandboxSandboxRouteImport } from './routes/_sandbox/sandbox'
import { Route as SandboxThemeRouteImport } from './routes/_sandbox/theme'
import { Route as UnauthedLoginIndexRouteImport } from './routes/_unauthed/login.index'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxRoute = SandboxRouteImport.update({
  id: '/_sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthedRoute = UnauthedRouteImport.update({
  id: '/_unauthed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedLogoutRoute = AuthedLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AuthedRoute,
} as any)
const SandboxBlocksRoute = SandboxBlocksRouteImport.update({
  id: '/blocks',
  path: '/blocks',
  getParentRoute: () => SandboxRoute,
} as any)
const SandboxSandboxRoute = SandboxSandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => SandboxRoute,
} as any)
const SandboxThemeRoute = SandboxThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => SandboxRoute,
} as any)
const UnauthedLoginIndexRoute = UnauthedLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => UnauthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof UnauthedRouteWithChildren
  '/logout': typeof AuthedLogoutRoute
  '/blocks': typeof SandboxBlocksRoute
  '/sandbox': typeof SandboxSandboxRoute
  '/theme': typeof SandboxThemeRoute
  '/login/': typeof UnauthedLoginIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof UnauthedRouteWithChildren
  '/logout': typeof AuthedLogoutRoute
  '/blocks': typeof SandboxBlocksRoute
  '/sandbox': typeof SandboxSandboxRoute
  '/theme': typeof SandboxThemeRoute
  '/login': typeof UnauthedLoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/_sandbox': typeof SandboxRouteWithChildren
  '/_unauthed': typeof UnauthedRouteWithChildren
  '/_authed/logout': typeof AuthedLogoutRoute
  '/_sandbox/blocks': typeof SandboxBlocksRoute
  '/_sandbox/sandbox': typeof SandboxSandboxRoute
  '/_sandbox/theme': typeof SandboxThemeRoute
  '/_unauthed/login/': typeof UnauthedLoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/logout' | '/blocks' | '/sandbox' | '/theme' | '/login/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/logout' | '/blocks' | '/sandbox' | '/theme' | '/login'
  id:
    | '__root__'
    | '/_authed'
    | '/_sandbox'
    | '/_unauthed'
    | '/_authed/logout'
    | '/_sandbox/blocks'
    | '/_sandbox/sandbox'
    | '/_sandbox/theme'
    | '/_unauthed/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  SandboxRoute: typeof SandboxRouteWithChildren
  UnauthedRoute: typeof UnauthedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sandbox': {
      id: '/_sandbox'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthed': {
      id: '/_unauthed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UnauthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/logout': {
      id: '/_authed/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof AuthedLogoutRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_sandbox/blocks': {
      id: '/_sandbox/blocks'
      path: '/blocks'
      fullPath: '/blocks'
      preLoaderRoute: typeof SandboxBlocksRouteImport
      parentRoute: typeof SandboxRoute
    }
    '/_sandbox/sandbox': {
      id: '/_sandbox/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof SandboxSandboxRouteImport
      parentRoute: typeof SandboxRoute
    }
    '/_sandbox/theme': {
      id: '/_sandbox/theme'
      path: '/theme'
      fullPath: '/theme'
      preLoaderRoute: typeof SandboxThemeRouteImport
      parentRoute: typeof SandboxRoute
    }
    '/_unauthed/login/': {
      id: '/_unauthed/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof UnauthedLoginIndexRouteImport
      parentRoute: typeof UnauthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedLogoutRoute: typeof AuthedLogoutRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedLogoutRoute: AuthedLogoutRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface SandboxRouteChildren {
  SandboxBlocksRoute: typeof SandboxBlocksRoute
  SandboxSandboxRoute: typeof SandboxSandboxRoute
  SandboxThemeRoute: typeof SandboxThemeRoute
}

const SandboxRouteChildren: SandboxRouteChildren = {
  SandboxBlocksRoute: SandboxBlocksRoute,
  SandboxSandboxRoute: SandboxSandboxRoute,
  SandboxThemeRoute: SandboxThemeRoute,
}

const SandboxRouteWithChildren =
  SandboxRoute._addFileChildren(SandboxRouteChildren)

interface UnauthedRouteChildren {
  UnauthedLoginIndexRoute: typeof UnauthedLoginIndexRoute
}

const UnauthedRouteChildren: UnauthedRouteChildren = {
  UnauthedLoginIndexRoute: UnauthedLoginIndexRoute,
}

const UnauthedRouteWithChildren = UnauthedRoute._addFileChildren(
  UnauthedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  SandboxRoute: SandboxRouteWithChildren,
  UnauthedRoute: UnauthedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
